// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M018.Models;

public partial class Address
{
    [Key]
    [Column("AddressID")]
    public int AddressId { get; set; }

    [Column("Address")]
    [StringLength(60)]
    [Unicode(false)]
    public string Address1 { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string City { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Region { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Country { get; set; }
}