// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace M018.Models;

[Keyless]
[Index("City", Name = "City")]
[Index("CompanyName", Name = "CompanyName")]
public partial class Customer
{
    [Required]
    [Column("CustomerID")]
    [StringLength(5)]
    [Unicode(false)]
    public string CustomerId { get; set; }

    [Required]
    [StringLength(40)]
    public string CompanyName { get; set; }

    [StringLength(30)]
    public string ContactName { get; set; }

    [StringLength(30)]
    public string ContactTitle { get; set; }

    [StringLength(60)]
    public string Address { get; set; }

    [StringLength(15)]
    public string City { get; set; }

    [StringLength(15)]
    public string Region { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string PostalCode { get; set; }

    [StringLength(15)]
    [Unicode(false)]
    public string Country { get; set; }

    [StringLength(24)]
    [Unicode(false)]
    public string Phone { get; set; }

    [StringLength(24)]
    [Unicode(false)]
    public string Fax { get; set; }
}